### ISSUE TITLE
gamenode crash

### ISSUE THREAD

**Issue by danj3000** [danj3000/ashteki#102]
an 11 07:58:32 PM  2021-01-11T19:58:32.871Z warn: Asked for config value 'keyPath' from section 'gameNode', but it was not configured
Jan 11 07:58:32 PM  2021-01-11T19:58:32.914Z info: Listening on 0.0.0.0:10000/gamenode1/socket.io
Jan 11 07:58:32 PM  2021-01-11T19:58:32.962Z info: syncing 0 games
Jan 11 07:58:40 PM  2021-01-11T19:58:40.404Z info: syncing 0 games
Jan 11 07:59:11 PM  2021-01-11T19:59:11.670Z info: syncing 0 games
Jan 12 05:35:12 PM  2021-01-12T17:35:12.224Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:12 PM  2021-01-12T17:35:12.232Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:19 PM  2021-01-12T17:35:19.724Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:19 PM  2021-01-12T17:35:19.728Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:21 PM  2021-01-12T17:35:21.757Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:21 PM  2021-01-12T17:35:21.760Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:22 PM  2021-01-12T17:35:22.549Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:22 PM  2021-01-12T17:35:22.550Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:30 PM  2021-01-12T17:35:30.763Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:30 PM  2021-01-12T17:35:30.765Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:36 PM  2021-01-12T17:35:36.792Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:36 PM  2021-01-12T17:35:36.795Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:39 PM  2021-01-12T17:35:39.188Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:39 PM  2021-01-12T17:35:39.190Z info: Cannot read property 'createContext' of undefined
Jan 12 05:35:56 PM  2021-01-12T17:35:56.284Z error: Cannot read property 'createContext' of undefined
Jan 12 05:35:56 PM  2021-01-12T17:35:56.286Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:05 PM  2021-01-12T17:36:05.946Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:05 PM  2021-01-12T17:36:05.948Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:08 PM  2021-01-12T17:36:08.322Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:08 PM  2021-01-12T17:36:08.325Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:08 PM  2021-01-12T17:36:08.819Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:08 PM  2021-01-12T17:36:08.820Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:09 PM  2021-01-12T17:36:09.204Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:09 PM  2021-01-12T17:36:09.205Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:13 PM  2021-01-12T17:36:13.461Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:13 PM  2021-01-12T17:36:13.464Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:14 PM  2021-01-12T17:36:14.387Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:14 PM  2021-01-12T17:36:14.388Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:24 PM  2021-01-12T17:36:24.522Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:24 PM  2021-01-12T17:36:24.524Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:45 PM  2021-01-12T17:36:45.061Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:45 PM  2021-01-12T17:36:45.064Z info: Cannot read property 'createContext' of undefined
Jan 12 05:36:45 PM  2021-01-12T17:36:45.807Z error: Cannot read property 'createContext' of undefined
Jan 12 05:36:45 PM  2021-01-12T17:36:45.809Z info: Cannot read property 'createContext' of undefined
Jan 12 05:37:30 PM  2021-01-12T17:37:30.291Z error: Cannot read property 'createContext' of undefined
Jan 12 05:37:30 PM  2021-01-12T17:37:30.292Z info: Cannot read property 'createContext' of undefined
Jan 12 05:37:30 PM  2021-01-12T17:37:30.319Z info: user 'Prattlesnake' disconnected from a game: client namespace disconnect
Jan 12 05:37:30 PM  2021-01-12T17:37:30.325Z info: Cannot read property 'createContext' of undefined
Jan 12 05:37:32 PM  ==> Starting service with 'node server/gamenode'
Jan 12 05:37:33 PM  2021-01-12T17:37:33.542Z warn: Asked for config value 'keyPath' from section 'gameNode', but it was not configured
Jan 12 05:37:33 PM  2021-01-12T17:37:33.553Z info: Listening on 0.0.0.0:10000/gamenode1/socket.io
Jan 12 05:37:33 PM  2021-01-12T17:37:33.581Z info: syncing 0 games
Jan 12 05:37:30 PM  TypeError: Cannot read property 'createContext' of undefined
    at /opt/render/project/src/server/game/Die.js:106:34
    at Array.filter (<anonymous>)
    at Die.getLegalActions (/opt/render/project/src/server/game/Die.js:105:27)
    at Die.getSummary (/opt/render/project/src/server/game/Die.js:49:22)
    at /opt/render/project/src/server/game/player.js:614:24
    at Array.map (<anonymous>)
    at Player.getSummaryForDiceList (/opt/render/project/src/server/game/player.js:613:21)
    at Player.getState (/opt/render/project/src/server/game/player.js:712:24)
    at Game.getState (/opt/render/project/src/server/game/game.js:1303:51)
    at GameServer.sendGameState (/opt/render/project/src/server/gamenode/gameserver.js:232:30)
Jan 12 05:38:03 PM  2021-01-12T17:38:03.002Z info: No game for Josh disconnecting
Jan 12 05:38:03 PM  2021-01-12T17:38:03.005Z info: No game for Josh disconnecting

JOSH game

**Comment by danj3000** [comment]
funky dice names - now validated in deckbuilder
